usb: dwc3: core: add the missing unified device interface replacement
Reference the commit 3d128919b7e5 (usb: dwc3: core: convert to unified device
property interface), use the unified device interface to replace the
"of_property*" APIs, here add the missed ones and to fix below build error:

drivers/usb/dwc3/core.c:989:6: error: 'node' undeclared (first use in this function)
|   if (node && of_dma_is_coherent(node)) {
|       ^~~~

Signed-off-by: Xulin Sun <xulin.sun@windriver.com>