ASoC:CNL:cnl_svfpga:Get codec from snd_soc_codec struct
commit afa2ecf81c1177e255646f9040a5bddc4a7e817f from
git://git@github.com:01org/linux-intel-4.9.git

codec list is part of snd_soc_codec.
This fixes below build error.
error: ‘struct snd_soc_component’ has no member named ‘card_list’

Change-Id: I69e2484082587f4d30a4b5692d282e76fba6de25
Signed-off-by: Pankaj Bharadiya <pankaj.laxminarayan.bharadiya@intel.com>