MLK-12392: arm: imx6q: fix lpddr2 build error if SMP is disabled
commit 21f09fb4cdd5e9e3f1dcd462d8e962183ce29f30 from
git://git.freescale.com/imx/linux-2.6-imx.git imx_4.1.15_1.0.0_ga

Fix build error if CONFIG_SMP is disabled:

arch/arm/mach-imx/busfreq_lpddr2.c: In function ‘update_lpddr2_freq_smp’:
arch/arm/mach-imx/busfreq_lpddr2.c:236:67: error: ‘me’ undeclared (first
use in this function)
  printk(KERN_DEBUG "Bus freq set to %d done! cpu=%d\n", ddr_rate, me);

Signed-off-by: Adrian Alonso <adrian.alonso@nxp.com>
Signed-off-by: Frank Li <Frank.Li@nxp.com>