arch/arm/mach-axxia: fix conflicting types compile error
Add prepend to functions in arch/arm/mach-axxia/axxia-gic.c to avoid
conflict with functions in drivers/irqchip/irq-gic.c. This patch fix
compile error as below:

arch/arm/mach-axxia/axxia-gic.c:660:13: error: conflicting types for 'gic_dist_save'
static void gic_dist_save(void)
            ^~~~~~~~~~~~~
In file included from arch/arm/mach-axxia/axxia-gic.c:41:0:
include/linux/irqchip/arm-gic.h:110:6: note: previous declaration of 'gic_dist_save' was here
void gic_dist_save(struct gic_chip_data *gic);
     ^~~~~~~~~~~~~
arch/arm/mach-axxia/axxia-gic.c:695:13: error: conflicting types for 'gic_dist_restore'
static void gic_dist_restore(void)
            ^~~~~~~~~~~~~~~~
In file included from arch/arm/mach-axxia/axxia-gic.c:41:0:
include/linux/irqchip/arm-gic.h:111:6: note: previous declaration of 'gic_dist_restore' was here
void gic_dist_restore(struct gic_chip_data *gic);
     ^~~~~~~~~~~~~~~~
arch/arm/mach-axxia/axxia-gic.c:731:13: error: conflicting types for 'gic_cpu_save'
static void gic_cpu_save(void)
            ^~~~~~~~~~~~
In file included from arch/arm/mach-axxia/axxia-gic.c:41:0:
include/linux/irqchip/arm-gic.h:108:6: note: previous declaration of 'gic_cpu_save' was here
void gic_cpu_save(struct gic_chip_data *gic);
     ^~~~~~~~~~~~
arch/arm/mach-axxia/axxia-gic.c:757:13: error: conflicting types for 'gic_cpu_restore'
static void gic_cpu_restore(void)
            ^~~~~~~~~~~~~~~
In file included from arch/arm/mach-axxia/axxia-gic.c:41:0:
include/linux/irqchip/arm-gic.h:109:6: note: previous declaration of 'gic_cpu_restore' was here
void gic_cpu_restore(struct gic_chip_data *gic);
     ^~~~~~~~~~~~~~~

Signed-off-by: Wang Quanyang <quanyang.wang@windriver.com>