crypto: caam/qi2 - fix compilation with DEBUG enabled
commit ce617caf41cd33fb813136c2a05364d5da3c581b from
https://github.com/qoriq-open-source/linux.git

Fix caam/qi2 driver compilation when DEBUG is enabled
(CRYPTO_DEV_FSL_CAAM_DEBUG=y):

drivers/crypto/caam/caamalg_qi2.c: In function 'aead_setkey':
drivers/crypto/caam/caamalg_qi2.c:528:38: error: 'key_in' undeclared
(first use in this function)
          DUMP_PREFIX_ADDRESS, 16, 4, key_in, keylen, 1);
                                      ^
drivers/crypto/caam/caamalg_qi2.c:528:38: note: each undeclared
identifier is reported only once for each function it appears in
drivers/crypto/caam/caamalg_qi2.c: In function 'aead_encrypt_done':
drivers/crypto/caam/caamalg_qi2.c:1573:61: error: 'err' undeclared
(first use in this function)
  dev_err(ctx->dev, "%s %d: err 0x%x\n", __func__, __LINE__, err);
                                                             ^
drivers/crypto/caam/caamalg_qi2.c: In function 'aead_decrypt_done':
drivers/crypto/caam/caamalg_qi2.c:1598:61: error: 'err' undeclared
(first use in this function)
  dev_err(ctx->dev, "%s %d: err 0x%x\n", __func__, __LINE__, err);
                                                             ^
drivers/crypto/caam/caamalg_qi2.c: In function 'ablkcipher_done':
drivers/crypto/caam/caamalg_qi2.c:1704:61: error: 'err' undeclared
(first use in this function)
  dev_err(ctx->dev, "%s %d: err 0x%x\n", __func__, __LINE__, err);
                                                             ^

Fixes: 21806c254f4a ("crypto: caam/qi2 - add DPAA2-CAAM driver")
Fixes: 3304cccd4732 ("crypto: caam/qi2 - add ablkcipher algorithms")
Reported-by: Radu Alexe <radu.alexe@nxp.com>
Signed-off-by: Horia Geantă <horia.geanta@nxp.com>
Signed-off-by: Meng Li <Meng.Li@windriver.com>