SoundWire: Fix compilation error
commit a816bdc14c503a054fe981a1401849af37a706a6 from
git://git@github.com:01org/linux-intel-4.9.git

/include/trace/events/sdw.h:166:9: error: initialization from incompatible \
pointer type [-Werror=incompatible-pointer-types]
         sdw_transfer_trace_reg,

Change-Id: Idb2934f4eedf23242d40e012b21c8d0d61ae4419
Signed-off-by: Pankaj Bharadiya <pankaj.laxminarayan.bharadiya@intel.com>