bcm2835-camera: fix compilation warning/werror
| /a/builder/mnt/build/tmp-glibc/work-shared/raspberrypi3/kernel-source/drivers/media/platform/bcm2835/bcm2835-camera.c:656:17: error: initialization from incompatible pointer type [-Werror=incompatible-pointer-types
]
|   .queue_setup = queue_setup,
|                  ^~~~~~~~~~~
| /a/builder/mnt/build/tmp-glibc/work-shared/raspberrypi3/kernel-source/drivers/media/platform/bcm2835/bcm28
35-camera.c:656:17: note: (near initialization for 'bm2835_mmal_video_qops.queue_setup')

use struct device* instead of void*

Signed-off-by: Khem Raj <raj.khem@gmail.com>
[Xulin: Original patch taken from
https://github.com/raspberrypi/linux.git branch rpi-4.8.y]
Signed-off-by: Xulin Sun <xulin.sun@windriver.com>