phy: keystone: remove unnecessary of_node_put()
This patch comes from:
  git://git.ti.com/processor-sdk/processor-sdk-linux.git

for_each_available_child_of_node() calls of_node_put()
on the previous child before returning the next
sibling. So, calling of_node_put() again within the
loop is totally unnecessary.

This causes the following error on k2hk evm while
booting:

ERROR: Bad of_node_put() on /soc/phy@232a000/lanes/lane@0

Fix it by removing the gratuitous of_node_put()

Tested-by: Murali Karicheri <m-karicheri2@ti.com>
Signed-off-by: Sekhar Nori <nsekhar@ti.com>
(cherry picked from commit eaa3e07cd7cfe06f856cb5a682af955132276aaa)
Signed-off-by: Zumeng Chen <zumeng.chen@windriver.com>