video: fbdev: xilinxfb: Fix multiple style issues from checkpatch
commit 7d32ced9e084b1cbafc77c22a872034a20ad9737 from
https://github.com/Xilinx/linux-xlnx.git

./scripts/checkpatch.pl --max-line-length 120 -strict -f
drivers/video/fbdev/xilinxfb.c
CHECK: Please don't use multiple blank lines
+
+

WARNING: Block comments should align the * on each line
+	/* Physical address of framebuffer memory; If non-zero, driver
+	* will use provided memory address instead of allocating one
from

WARNING: Block comments use a trailing */ on a separate line
+	* the consistent pool. */

CHECK: Please don't use multiple blank lines
+
+

CHECK: Blank lines aren't necessary after an open brace '{'
+struct xilinxfb_drvdata {
+

WARNING: Block comments use * on subsequent lines
+	phys_addr_t	regs_phys;	/* phys. address of the control
+						registers */

WARNING: Block comments use a trailing */ on a separate line
+						registers */

WARNING: Block comments use * on subsequent lines
+	void __iomem	*regs;		/* virt. address of the control
+						registers */

WARNING: Block comments use a trailing */ on a separate line
+						registers */

WARNING: please, no space before tabs
+^Iu8 ^I^Iflags;^I^I/* features of the driver */$

CHECK: Alignment should match open parenthesis
+static void xilinx_fb_out32(struct xilinxfb_drvdata *drvdata, u32
offset,
+				u32 val)

WARNING: Prefer 'unsigned int' to bare use of 'unsigned'
+xilinx_fb_setcolreg(unsigned regno, unsigned red, unsigned green,
unsigned blue,

WARNING: Prefer 'unsigned int' to bare use of 'unsigned'
+xilinx_fb_setcolreg(unsigned regno, unsigned red, unsigned green,
unsigned blue,

WARNING: Prefer 'unsigned int' to bare use of 'unsigned'
+xilinx_fb_setcolreg(unsigned regno, unsigned red, unsigned green,
unsigned blue,

WARNING: Prefer 'unsigned int' to bare use of 'unsigned'
+xilinx_fb_setcolreg(unsigned regno, unsigned red, unsigned green,
unsigned blue,

CHECK: Alignment should match open parenthesis
+xilinx_fb_setcolreg(unsigned regno, unsigned red, unsigned green,
unsigned blue,
+	unsigned transp, struct fb_info *fbi)

WARNING: Prefer 'unsigned int' to bare use of 'unsigned'
+	unsigned transp, struct fb_info *fbi)

WARNING: Block comments use a trailing */ on a separate line
+		 * grayscale = 0.30*R + 0.59*G + 0.11*B */

CHECK: multiple assignments should be avoided
+		red = green = blue =

+
+	}

ERROR: that open brace { should be on the previous line
+static struct fb_ops xilinxfb_ops =
+{

CHECK: 'Endianess' may be misspelled - perhaps 'Endianness'?
+	/* Endianess detection */

CHECK: Alignment should match open parenthesis
+	xilinx_fb_out32(drvdata, REG_CTRL,
+					drvdata->reg_ctrl_default);

CHECK: Alignment should match open parenthesis
+		dma_free_coherent(dev, PAGE_ALIGN(fbsize),
drvdata->fb_virt,
+			drvdata->fb_phys);

WARNING: braces {} are not necessary for single statement blocks
+	if (tft_access) {
+		drvdata->flags |= BUS_ACCESS_FLAG;
+	}

WARNING: Missing a blank line after declarations
+		int start;
+		start = dcr_resource_start(pdev->dev.of_node, 0);

CHECK: spaces preferred around that '*' (ctx:VxV)
+	if ((prop) && (size >= sizeof(u32)*2)) {
 	                                  ^

CHECK: spaces preferred around that '*' (ctx:VxV)
+	if ((prop) && (size >= sizeof(u32)*2)) {
 	                                  ^

CHECK: spaces preferred around that '*' (ctx:VxV)
+	if ((prop) && (size >= sizeof(u32)*2)) {
 	                                  ^

WARNING: struct of_device_id should normally be const
+static struct of_device_id xilinxfb_of_match[] = {

Signed-off-by: Hyun Kwon <hyun.kwon@xilinx.com>
Signed-off-by: Michal Simek <michal.simek@xilinx.com>
Signed-off-by: Xulin Sun <xulin.sun@windriver.com>