fsl/Rman: change rman kernel option from bool to tristate
Because rman depends on UIO subsystem, when UIO is built as
kernel module, rman should be changed to module state too.
So change rman kernel option from bool to tristate or it will
occurr building error as below when CONFIG_UIO=m:

drivers/staging/fsl_rman/rman_uio_driver.c:235: undefined reference to `.uio_unregister_device'
drivers/built-in.o: In function `fsl_rman_remove':
drivers/staging/fsl_rman/rman_uio_driver.c:337: undefined reference to `.uio_unregister_device'
drivers/built-in.o: In function `rman_ib_uio_init':
drivers/staging/fsl_rman/rman_uio_driver.c:169: undefined reference to `.__uio_register_device'
drivers/built-in.o: In function `rman_uio_init':
drivers/staging/fsl_rman/rman_uio_driver.c:144: undefined reference to `.__uio_register_device'
drivers/built-in.o: In function `fsl_rman_ib_remove':
drivers/staging/fsl_rman/rman_uio_driver.c:235: undefined reference to `.uio_unregister_device'

Signed-off-by: Quanyang Wang <quanyang.wang@windriver.com>