ktree: build as obj-y rather than lib-y
This patch is to fix potential exported symbols undefined because they might
be discarded due to no users in vmlinux when the only user is configured as
kernel module.

ERROR: "ktree_init" [drivers/soc/ti/knav_qmss_qos.ko] undefined!
ERROR: "ktree_put_node" [drivers/soc/ti/knav_qmss_qos.ko] undefined!
ERROR: "ktree_set_root" [drivers/soc/ti/knav_qmss_qos.ko] undefined!
ERROR: "ktree_sort_children" [drivers/soc/ti/knav_qmss_qos.ko] undefined!
ERROR: "ktree_add_child_before" [drivers/soc/ti/knav_qmss_qos.ko] undefined!
ERROR: "ktree_for_each_child" [drivers/soc/ti/knav_qmss_qos.ko] undefined!
ERROR: "ktree_remove_node" [drivers/soc/ti/knav_qmss_qos.ko] undefined!
scripts/Makefile.modpost:91: recipe for target '__modpost' failed
make[1]: *** [__modpost] Error 1

Signed-off-by: Zumeng Chen <zumeng.chen@windriver.com>