can: flexcan: fix the typo and missing variables
To fix a typo and below errors:
drivers/net/can/flexcan.c:1338:3: error: 'core_is_little' undeclared (first use in this function)
|    core_is_little = false;
|    ^~~~~~~~~~~~~~

Signed-off-by: Xulin Sun <xulin.sun@windriver.com>