ARM: OMAP: AM43xx: fix build when SUSPEND=n
Fix am43xx only build when CONFIG_SUSPEND=n

arch/arm/mach-omap2/built-in.o: In function `am43xx_suspend':
arch/arm/mach-omap2/pm33xx-core.c:177: undefined reference to `cpu_suspend'
arch/arm/mach-omap2/built-in.o: In function `resume_addr':
arch/arm/mach-omap2/sleep43xx.S:403: undefined reference to `cpu_resume'
make: *** [vmlinux] Error 1

Signed-off-by: Grygorii Strashko <grygorii.strashko@ti.com>
Signed-off-by: Dave Gerlach <d-gerlach@ti.com>
(cherry picked from commit c4b658f8ff2be48fd5a64a154e6f98a3efda2552)