dma: xilinx: Fix compilation errors in the DMA test clients
Fixed compilation errors in the DMA test clients caused by:
"dmaengine: xilinx-dma: move header file to common location"
(sha1: 937abe88aea3161cd3a563e577fc9cf4522c7aad).

These errors are due to the header file location change.

This patch fixes the below compilation errors.
CC      drivers/dma/xilinx/axidmatest.o
drivers/dma/xilinx/axidmatest.c:22:35: fatal error: linux/amba/xilinx_dma.h: No such file or directory
 #include <linux/amba/xilinx_dma.h>
  CC      drivers/dma/xilinx/cdmatest.o
drivers/dma/xilinx/cdmatest.c:22:35: fatal error: linux/amba/xilinx_dma.h: No such file or directory
 #include <linux/amba/xilinx_dma.h>
  CC      drivers/dma/xilinx/vdmatest.o
drivers/dma/xilinx/vdmatest.c:20:35: fatal error: linux/amba/xilinx_dma.h: No such file or directory
 #include <linux/amba/xilinx_dma.h>

Signed-off-by: Kedareswara rao Appana <appanad@xilinx.com>
Signed-off-by: Michal Simek <michal.simek@xilinx.com>