MLK-11985-1 ARM: imx: fix coverity scan issues
commit 5c8f42c67d94bc4347401e49d6bc2895662f3333 from
git://git.freescale.com/imx/linux-2.6-imx.git imx_4.1.15_1.0.0_ga

1. Add return value check to fix below warning:

check_return: Calling of_property_read_u32 without
checking return value.

2. Improve code to fix below warning:

copy_paste_error: i in of_clk_get(dev->of_node, i)
looks like a copy-paste error.

Signed-off-by: Anson Huang <Anson.Huang@freescale.com>