driver: qman: Unify API of getting cpu id on arm64 and ppc platform
when build kernel on arm64 platdorm, there is a build error as below:
drivers/staging/fsl_qbman/qman_driver.c:607:4: error: implicit declaration
of function 'get_hard_smp_processor_id' [-Werror=implicit-function-declaration]
get_hard_smp_processor_id(raw_smp_processor_id()));
^~~~~~~~~~~~~~~~~~~~~~~~~

Because in arm64 platform, there is no get_hard_smp_processor_id(),
use hard_smp_processor_id() to replace it. On ppc platform, it also
supports function hard_smp_processor_id(), so it will not cause build
error.

Signed-off-by: Meng Li <Meng.Li@windriver.com>