net: emacps: Add missing dependency for PTP
Error log:
  drivers/built-in.o: In function `xemacps_init_hw':
  :(.text+0xf8720): undefined reference to `ptp_clock_register'
  :(.text+0xf873c): undefined reference to `ptp_clock_index'
  drivers/built-in.o: In function `xemacps_close':
  :(.text+0xf8e78): undefined reference to `ptp_clock_unregister'
  make: *** [vmlinux] Error 1

Reported-by: Soren Brinkmann <soren.brinkmann@xilinx.com>
Signed-off-by: Michal Simek <michal.simek@xilinx.com>