trusty: fix incompatible-pointer-types
commit 874e2832eaefe3e0fe7285e3ad5689f85083a117 from
git://git@github.com:01org/linux-intel-4.9.git

incompatible-pointer-types found in function trusty_virtio_find_vps

drivers/trusty/trusty-virtio.c:380:14: error: initialization from
incompatible pointer type [-Werror=incompatible-pointer-types]
  .find_vqs = trusty_virtio_find_vqs,

Signed-off-by: Dwane Pottratz <dwane.pottratz@intel.com>