Fix compilation error
commit 6ad6ace617af2d391f9e5828b2a96fa746f63d1b from
git://git@github.com:01org/linux-intel-4.9.git

sound/soc/intel/skylake/skl-messages.c:36:28: fatal error: asm/set_memory.h: No such file or directory
compilation terminated.
scripts/Makefile.build:293: recipe for target 'sound/soc/intel/skylake/skl-messages.o' failed
make[4]: *** [sound/soc/intel/skylake/skl-messages.o] Error 1
scripts/Makefile.build:544: recipe for target 'sound/soc/intel/skylake' failed

Change-Id: Ie48f4d47d95ced73dff23028e377ee36657add50
Tracked-On:
Signed-off-by: Pankaj Bharadiya <pankaj.laxminarayan.bharadiya@intel.com>