rpmsg: add the missing head files
To fix below building errors:
| drivers/rpmsg/rpmsg_core.c:320:9: error: implicit declaration of function 'of_driver_match_device' [-Werror=implicit-function-declaration]
|   return of_driver_match_device(dev, drv);
|          ^~~~~~~~~~~~~~~~~~~~~~

Signed-off-by: Xulin Sun <xulin.sun@windriver.com>