ASoC:CNL:cnl_cs42l42:Get codec from snd_soc_codec struct
commit f8ff47f3f74ebf9b42cae72f056b9fba8e40f560 from
git://git@github.com:01org/linux-intel-4.9.git

codec list is part of snd_soc_codec.
This fixes below build error.
error: ‘struct snd_soc_component’ has no member named ‘card_list’

Change-Id: I127fb2a1f671fe3179a6f2f4cb6d95b7f7205f19
Signed-off-by: Pankaj Bharadiya <pankaj.laxminarayan.bharadiya@intel.com>