driver: ls2-console: there is no need to check the return value of misc_deregister() function
there is a build error as below:
drivers/soc/fsl/ls2-console/ls2-console.c:249:12: error: void value not
ignored as it ought to be
	int err = misc_deregister(&fsl_ls2_mc_console_dev);
	^~~~~~~~~~~~~~~

Because in linux 4.8 kernel, misc_deregister() doesn’t has return value,
delete variable err and condition judgement where use err.

Signed-off-by: Meng Li <Meng.Li@windriver.com>