crypto: Convert to new AEAD interface
This patch converts testmgr and cryptlib to the new AEAD interface,
it is to fix the below error:

crypto/testmgr.c:1090:3: error: implicit declaration of function 'aead_request_set_assoc' [-Werror=implicit-function-declaration]
    aead_request_set_assoc(req, asg, template[i].alen);
        ^

Signed-off-by: Yanjiang Jin <yanjiang.jin@windriver.com>
[Adjust context to fit in 4.8.8]
Signed-off-by: Yang Shi <yang.shi@windriver.com>