net: ethernet: xilinx: bug fix for missing phydev var
Fixes the following compilation error when CONFIG_XILINX_AXI_EMAC is
enabled:
...
drivers/net/ethernet/xilinx/xilinx_axienet_main.c:1513:6: error:
phydev' undeclared (first use in this function)
|   if (phydev)
...

This fix is specific to the Windriver xilinx-zynq kernel (the compilation
issue was introduced by commit 0031e853a0496a96fc30c080c63862961ecced34).

Signed-off-by: Ovidiu Panait <ovidiu.panait@windriver.com>