arm: Add __aeabi_uldivmod 64-bits divider function
The tmc_update_etr_buffer() (coresight-tmc-etr.c:764) uses 64-bit division
for calculating rrp. The linker complains about missing __aeabi_uldivmod as follows:

drivers/built-in.o: In function `tmc_update_etr_buffer':
| drivers/hwtracing/coresight/coresight-tmc-etr.c:764: undefined reference to `__aeabi_uldivmod'
| make[2]: *** [Makefile:949: vmlinux] Error 1
| make[1]: *** [Makefile:150: sub-make] Error 2
| make: *** [Makefile:24: __sub-make] Error 2

Signed-off-by: Jianchuan Wang <jianchuan.wang@windriver.com>