fsl_qbman: fix a qman compile error
This is to fix the below error:
drivers/staging/fsl_qbman/qman_test_high.c: In function 'cb_dqrr':
include/linux/kern_levels.h:4:18: error:
 format '%llx' expects argument of type 'long long unsigned int', but argument 2 has type 'int' [-Werror=format=]

Signed-off-by: Yanjiang Jin <yanjiang.jin@windriver.com>